services:
  app:
    container_name: app
    env_file:
      - docker.env
    build:
      context: ./
      dockerfile: Dockerfile
    image: app-latest
    ports:
      - 3000:3000
  db:
    container_name: db
    env_file:
      - db/docker.env
    build:
      context: ./
      dockerfile: db/Dockerfile
    image: db-latest
    ports:
      - 5432:5432
